#!/usr/bin/env python3

import os
import sys

sys.path.append(".")
from posixpath import join as pjoin

from datasets.bvh_parser import BVH_file
from datasets.bvh_writer import BVH_writer
from models.IK import fix_foot_contact


# downsampling and remove redundant joints
def copy_ref_file(src, dst):
    file = BVH_file(src)
    writer = BVH_writer(file.edges, file.names)
    writer.write_raw(file.to_tensor(quater=True)[..., ::2], "quaternion", dst)


def get_height(file):
    file = BVH_file(file)
    return file.get_height()


def example(
    src_name, src_bvh, dest_armature, dest_name, bvh_name, test_type, output_path
):
    if not os.path.exists(output_path):
        os.makedirs(output_path)

    input_file = "./datasets/Mixamo/{}/{}".format(src_name, src_bvh)
    copy_ref_file(input_file, pjoin(output_path, "input.bvh"))

    ref_file = './datasets/Mixamo/{}/{}'.format(dest_name, bvh_name)
    copy_ref_file(ref_file, pjoin(output_path, 'gt.bvh'))
    height = get_height(input_file)

    bvh_name = bvh_name.replace(" ", "_")
    input_file = "./datasets/Mixamo/{}/{}".format(src_name, bvh_name)
    ref_file = "./datasets/Mixamo/{}/{}".format(dest_name, bvh_name)
    cmd = "python eval_single_pair.py --input_bvh={} --target_armature={} --target_bvh={} --output_filename={} --test_type={}".format(
        input_file, dest_armature, ref_file, pjoin(output_path, "result.bvh"), test_type
    )
    err = os.system(cmd)
    if err:
        return err
    fix_foot_contact(
        pjoin(output_path, "result.bvh"),
        pjoin(output_path, "input.bvh"),
        pjoin(output_path, "result.bvh"),
        height,
    )


if __name__ == "__main__":
    # Ensure FBX has multiple of 64 frames
    # blender -b -P fbx2bvh.py
    # python3 datasets/split_joint.py # Optional
    # python3 datasets/preprocess.py
    # python3 .\demo
    err = 0
    if err == 0:
        example(
            src_name="SportyGranny",
            src_bvh="Dancing Running Man.bvh",
            dest_armature="Kaya",
            dest_name="Kaya",
            bvh_name="Dancing Running Man.bvh",
            test_type="intra",
            output_path="./examples/intra_structure",
        )
    if err == 0:
        example(
            src_name="BigVegas",
            src_bvh="Dual Weapon Combo.bvh",
            dest_armature="Mousey_m",
            dest_name="Mousey_m",
            bvh_name="Dual Weapon Combo.bvh",
            test_type="cross",
            output_path="./examples/cross_structure",
        )
