#!/usr/bin/env python3

from models.IK import fix_foot_contact
from datasets.bvh_writer import BVH_writer
from datasets.bvh_parser import BVH_file
from posixpath import join as pjoin
import os
import sys

sys.path.append(".")


# downsampling and remove redundant joints
def copy_ref_file(src, dst):
    file = BVH_file(src)
    writer = BVH_writer(file.edges, file.names)
    writer.write_raw(file.to_tensor(quater=True)[..., ::2], "quaternion", dst)


def get_height(file):
    file = BVH_file(file)
    return file.get_height()


def example(
    src_name, src_bvh, dst_name, dst_bvh, output_path
):
    if not os.path.exists(output_path):
        os.makedirs(output_path)

    input_file = f"./datasets/Motions/{src_name}/{src_bvh}"
    input_path = f"{src_name}_{src_bvh}_input.bvh"
    copy_ref_file(input_file, pjoin(output_path,))

    ref_file = f'./datasets/Motions/{dst_name}/{dst_bvh}'
    reference_path = f'{dst_name}_{dst_bvh}_reference.bvh'
    copy_ref_file(ref_file, pjoin(output_path, reference_path))
    height = get_height(input_file)

    input_file = f"./datasets/Motions/{src_name}/{src_bvh}"
    ref_file = f"./datasets/Motions/{dst_name}/{dst_bvh}"

    result_path = f"{src_name}_{src_bvh}_result.bvh"
    joined_output_path = pjoin(output_path, result_path)
    cmd = f"python eval_single_pair.py --input_bvh={input_file} --target_bvh={ref_file} --output_filename={joined_output_path}"
    err = os.system(cmd)
    if err:
        return err
    fix_foot_contact(
        pjoin(output_path, result_path),
        pjoin(output_path, input_path),
        pjoin(output_path, result_path),
        height,
    )


if __name__ == "__main__":
    example(
        src_name="BerkeleyMHAD_skl_s11",
        src_bvh="skl_s11_a09_r04.bvh",
        dst_name="BerkeleyMHAD_skl_s01",
        dst_bvh="skl_s01_a07_r03.bvh",
        output_path="./examples",
    )